server:
  port: 8766
spring:
  application:
    name: auth
  profiles:
    active: dev
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: hxh916App
  clientSecret: hxh916App
  cookieDomain: hxh916.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/hxh.keystore
    secret: huxiaohuikeystore
    alias: hxhkey
    password: huxiaohui

