spring:
  application:
    name: authorization-server
server:
  port: 8766
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: hxh916App
  clientSecret: hxh916App
  cookieDomain: hxh916.com
  cookieMaxAge: -1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
